---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MongoDB
  apt:
    name: mongodb-org
    state: present
    update_cache: yes

- name: Create data directory
  file:
    path: /data/db
    state: directory
    owner: mongodb
    group: mongodb
    mode: '0755'

- name: Copy mongod.conf template
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart MongoDB

- name: Start and enable MongoDB service
  service:
    name: mongod
    state: started
    enabled: yes

- name: Wait for MongoDB to be ready
  wait_for:
    host: localhost
    port: "{{ mongodb_port }}"
    timeout: 30

- name: Set MongoDB master and replica IPs
  set_fact:
    mongodb_master_ip: "{{ hostvars[groups['_infra_server'][0]]['private_ip_address'] }}"
    mongodb_replica_ip: "{{ private_ip_address }}"
  when: "'_infra_server' in groups and groups['_infra_server'] | length > 1"

- name: Create replica set initiation script
  template:
    src: rs_init.js.j2
    dest: /tmp/rs_init.js

- name: Wait until MongoDB is ready to accept replica set initiation
  shell: |
    until mongosh --quiet --eval "db.adminCommand('ping')"; do
      sleep 5
    done
  register: ping_result
  until: ping_result.rc == 0
  retries: 10
  delay: 5
  delegate_to: "{{ mongodb_master_ip }}"
  run_once: true

- name: Initiate MongoDB replica set with retries
  shell: |
    mongosh --quiet --host {{ mongodb_master_ip }} --eval "
      try {
        rs.initiate({
          _id: '{{ mongodb_replset }}',
          members: [
            { _id: 0, host: '{{ mongodb_master_ip }}:27017', priority: 2 },
            { _id: 1, host: '{{ mongodb_replica_ip }}:27017', priority: 1 }
          ]
        })
      } catch (e) {
        if (e.codeName === 'AlreadyInitialized') {
          print('Replica set already initialized');
        } else {
          throw e;
        }
      }
    "
  register: rs_init
  until: "'ok' in rs_init.stdout"
  retries: 5
  delay: 10
  delegate_to: "{{ mongodb_master_ip }}"
  run_once: true

- name: Verify replica set status
  shell: |
    mongosh --quiet --host {{ mongodb_master_ip }} --eval "
      var status = rs.status();
      if (status.members.length == 2 && 
          status.members.some(m => m.stateStr == 'PRIMARY') && 
          status.members.some(m => m.stateStr == 'SECONDARY')) {
        print('ok');
      } else {
        print('not ready');
      }
    "
  register: rs_status
  until: "'ok' in rs_status.stdout"
  retries: 10
  delay: 5
  delegate_to: "{{ mongodb_master_ip }}"
  run_once: true
